// 全コンポーネントを登録して再エクスポートする（CDN バンドルの入口）
export * from './components/alert/index.js'
export * from './components/badge/index.js'
export * from './components/button/index.js'
export * from './components/card/index.js'
export * from './components/checkbox/index.js'
export * from './components/field/index.js'
export * from './components/input/index.js'
export * from './components/radio-group/index.js'
export * from './components/switch/index.js'
export * from './components/textarea/index.js'
export { getLocale, setLocale, setMessages } from './i18n/index.js'
export type { Locale, MessageKey } from './i18n/index.js'
