// 全コンポーネントを登録して再エクスポートする（CDN バンドルの入口）
export * from './components/alert/index.js'
export * from './components/app-shell/index.js'
export * from './components/badge/index.js'
export * from './components/breadcrumb/index.js'
export * from './components/button/index.js'
export * from './components/card/index.js'
export * from './components/checkbox/index.js'
export * from './components/color-input/index.js'
export * from './components/combobox/index.js'
export * from './components/date-input/index.js'
export * from './components/description-list/index.js'
export * from './components/dialog/index.js'
export * from './components/drawer/index.js'
export * from './components/dropdown-menu/index.js'
export * from './components/dual-listbox/index.js'
export * from './components/kanban/index.js'
export * from './components/field/index.js'
export * from './components/file-input/index.js'
export * from './components/icon/index.js'
export * from './components/input/index.js'
export * from './components/page-header/index.js'
export * from './components/pagination/index.js'
export * from './components/radio-group/index.js'
export * from './components/router/index.js'
export * from './components/select/index.js'
export * from './components/sidebar-nav/index.js'
export * from './components/spinner/index.js'
export * from './components/switch/index.js'
export * from './components/table/index.js'
export * from './components/tabs/index.js'
export * from './components/textarea/index.js'
export * from './components/toast/index.js'
export * from './components/tooltip/index.js'
// すべてのアイコンを登録する(個別に読み込むときは @hidemikimura/jimble-ui/icons/<name>)
import './icons/register/index.js'
export { getLocale, setLocale, setMessages } from './i18n/index.js'
export type { Locale, MessageKey } from './i18n/index.js'
export { JimbleUI, installGlobal } from './global.js'
